### PR TITLE
cross publish to 2.12

### LINKED ISSUE #71: Cross publish for scala 2.12
Any chance this could be cross-published for scala 2.12?

### PR DESCRIPTION
**Pull request by joprice**
closes #71

### CODE REVIEW

**Comment by joprice** [comment]
I made these changes mechanically. I haven't tried publishing local yet and insuring no weird runtime issues happen. I was planning on doing that sometime this week.

**Comment by lucagiovagnoli** [comment]
Thanks for taking care of this @joprice, let me know if it works.

- [ ] Test publishLocal
- [ ] Test the package at runtime

**Comment by lucagiovagnoli** [comment]
Any update on testing, @joprice ?

**Comment by joprice** [comment]
Unfortunately, I haven't had the time yet. I'll try to test it tomorrow.

**Comment by joprice** [comment]
I was able to `+publishLocal` and use this locally in a project and it worked as expected.

**Comment by lucagiovagnoli** [comment]
This looks great @joprice. I'll work on merging this and publishing

**Review by jsleight — APPROVED** [review]

**Pull request merged**
